'use strict';
// Стандартный набор теста: черты идеологий, темы, партии, вопросы, вопросы о системе и готовые пресеты.
// Эти константы читает js/app.js.
// ══════ Стандартный набор: черты идеологий, темы, партии, вопросы ══════
// Позицию партии по вопросу никто не задаёт вручную: она выводится из её черт и черт, привязанных к вариантам A и B.
const TR=[
  ['gos','State regulation','Economy'],['mkt','Free market','Economy'],['tax_hi','High taxes and redistribution','Economy'],['tax_lo','Low taxes','Economy'],
  ['labor','Workers’ protection','Economy'],['biz','Business freedom','Economy'],['nat','State ownership','Economy'],['priv','Privatisation','Economy'],['prot','Protectionism','Economy'],
  ['welfare','Welfare state','Social policy'],['self','Personal responsibility','Social policy'],['pub','Public services','Social policy'],['choice','Private choice in services','Social policy'],['equal','Egalitarianism','Social policy'],
  ['prog','Progressivism','Values'],['trad','Traditionalism','Values'],['sec','Secularism','Values'],['rel','Religiosity','Values'],['lib','Personal freedoms','Values'],['soviet','Soviet legacy','Values'],
  ['auth','Authoritarianism','Power and order'],['law','Tough punishment','Power and order'],['rehab','Humane justice','Power and order'],['privacy','Privacy protection','Power and order'],
  ['mil','Militarism','Power and order'],['pac','Pacifism','Power and order'],['pop','Populism','Power and order'],['tech','Technocracy','Power and order'],['direct','Direct democracy','Power and order'],['pres','Strong presidency','Power and order'],['parl','Parliamentarism','Power and order'],['stab','Stability and continuity','Power and order'],['plural','Political competition','Power and order'],
  ['imm_pro','Pro-immigration','Migration'],['imm_anti','Anti-immigration','Migration'],['multi','Multiculturalism','Migration'],['assim','Assimilation','Migration'],
  ['fed','Regionalism','Territory'],['cent','Centralism','Territory'],['sep','Right to self-determination','Territory'],['unity','Unity of the country','Territory'],['lang_min','Minority languages','Territory'],['lang_one','Single state language','Territory'],
  ['eco','Environmentalism','Environment'],['growth','Growth first','Environment'],['agr','Agrarianism','Environment'],
  ['euro','European integration','World'],['sov','Sovereigntism','World'],['nation','Nationalism','World'],['cosmo','Internationalism','World'],
  ['west','Rapprochement with the West','World'],['antiwest','Confrontation with the West','World'],['eurasia','Eurasian integration','World']
];
const DEF_T=[
  ['Economy and employment','Taxes, labour, business','#94A8F9','More state','More market'],
  ['Public services','Healthcare, pensions, housing','#6DCAAE','More public provision','More private choice'],
  ['Society and values','Freedoms, traditions','#EF92B3','Social change','Tradition'],
  ['Security and justice','Crime, prisons, defence','#9DA4B1','More prevention','More toughness'],
  ['Immigration','Entry, integration','#F9C566','More openness','More control'],
  ['Territorial organisation','Autonomies, languages','#E8916F','More self-government','More centralisation'],
  ['The environment','Energy, water, pollution','#7DB889','Environment first','Growth first'],
  ['Europe','European Union, sovereignty','#77B1E6','More European integration','More national sovereignty']
];
// Сила черты: 1 — слабо, 2 — умеренно, 3 — сильно
const DEF_F=[
  ['The Left','#A3192F','A very large public sector, strong redistribution and criticism of the current economic model.',
    {gos:3,tax_hi:3,labor:3,nat:3,prot:2,welfare:3,pub:3,equal:3,prog:3,sec:3,lib:2,rehab:3,privacy:3,pac:3,imm_pro:3,multi:3,fed:1,sep:2,lang_min:2,eco:2,sov:1,cosmo:2}],
  ['Social Democrats','#E4312B','A market economy with a developed welfare state, gradual reforms and the European project.',
    {gos:2,tax_hi:2,labor:2,nat:1,prot:1,welfare:2,pub:2,equal:3,prog:2,sec:2,lib:2,rehab:1,privacy:1,mil:1,imm_pro:1,multi:1,unity:1,lang_min:1,eco:2,agr:1,euro:2,cosmo:1}],
  ['Greens and Regionalists','#3BA55C','Ecology at the centre, a progressive approach and more self-government for the territories.',
    {gos:2,tax_hi:2,labor:2,nat:1,prot:1,welfare:2,pub:2,equal:3,prog:3,sec:2,lib:3,rehab:2,privacy:2,pac:1,imm_pro:3,multi:3,fed:3,sep:3,lang_min:3,eco:3,euro:2,cosmo:2}],
  ['Liberals','#EDB91E','An open market, broad personal freedoms and a firm commitment to European integration.',
    {mkt:3,tax_lo:2,biz:2,priv:2,self:1,choice:2,prog:1,sec:2,lib:3,privacy:2,mil:2,imm_pro:1,cent:1,unity:1,euro:3,cosmo:2}],
  ['Christian Democrats','#4FA3E0','The centre-right: a social market economy, institutional stability and the European project.',
    {mkt:1,tax_lo:1,biz:1,priv:1,self:1,choice:2,trad:2,rel:2,law:2,mil:2,imm_anti:1,assim:1,cent:1,unity:3,lang_one:1,growth:1,agr:2,euro:2}],
  ['Conservatives','#1E4FA0','The market, traditional values, toughness on security and a Europe of nations.',
    {mkt:2,tax_lo:3,biz:2,priv:2,self:2,choice:2,trad:2,rel:2,auth:2,law:3,mil:3,imm_anti:2,assim:2,cent:2,unity:3,lang_one:2,growth:2,agr:2,sov:2,nation:2}],
  ['National Conservatives','#7A4E2D','Priority for national identity, border control and sovereignty over the EU.',
    {mkt:1,tax_lo:2,prot:1,welfare:1,self:2,trad:3,rel:2,auth:3,law:3,mil:1,imm_anti:3,assim:3,cent:3,unity:3,lang_one:3,growth:3,agr:3,sov:3,nation:3}]
];
// [тема, d (+1: вариант B ведёт к правому полюсу темы), заголовок, A, B, черты A, черты B]
const DEF_Q=[
  [0,1,'Taxes','Raise taxes to have more public services','Cut taxes, even if there are fewer services',['tax_hi','welfare'],['tax_lo']],
  [0,-1,'Employment','More flexibility in hiring and firing, even if jobs become less stable','More protection against dismissal, even if hiring becomes more expensive',['biz'],['labor']],
  [0,1,'Minimum wage','Raise it sharply to lift the lowest wages','Raise it moderately so as not to slow hiring',['labor'],['biz']],
  [0,-1,'Strategic companies','Let them stay in private hands','The state should have a stake in them',['priv'],['nat']],
  [0,1,'Large fortunes','A specific tax on large fortunes','No specific taxes on wealth',['tax_hi'],['tax_lo']],
  [0,-1,'Aid to industries','Fewer subsidies; let the market adjust by itself','More public aid to industries in difficulty',['mkt'],['prot']],
  [1,-1,'Healthcare','Combine public and private healthcare so that patients can choose','Concentrate resources on strong public healthcare',['choice'],['pub']],
  [1,1,'Pensions','Public only, even if contributions have to rise','Public and private, even if a pension depends more on personal savings',['pub','welfare'],['choice']],
  [1,1,'Housing','Cap rents to make housing more affordable','No price caps; make it easier to build new housing',['gos'],['mkt']],
  [1,-1,'Education','Also fund state-subsidised private schools with public money','Concentrate the money on public schools',['choice','rel'],['pub']],
  [1,1,'Running public services','Let the state run them directly to keep public control','Let private companies run them when it is cheaper',['pub','gos'],['priv']],
  [1,-1,'Social assistance','Targeted benefits tied to looking for work','A broad system that guarantees a minimum income',['self'],['welfare']],
  [2,1,'Way of life','Everyone decides how to live, and the law should not interfere','The law should protect shared values',['lib'],['trad','auth']],
  [2,-1,'Traditions','They are part of our identity and must be preserved','They should change with the times',['trad'],['prog']],
  [2,1,'Social change','Adopt them when there is a majority, even without broad consensus','Wait for broad consensus, even if change takes longer',['prog'],['trad']],
  [2,1,'Religion','Complete separation of state institutions and religion','Recognise the role of religion in society',['sec'],['rel']],
  [2,-1,'Teaching values','Teaching values is a matter for the family','School also teaches shared values such as equality',['trad'],['equal','prog']],
  [2,-1,'Equality','Equality before the law is enough','Active policies to correct inequalities',['trad'],['equal']],
  [3,-1,'Crime','More police and harsher sentences','More prevention and rehabilitation',['law','auth'],['rehab']],
  [3,1,'Prisons','Priority: returning prisoners to society','Priority: serving sentences in full',['rehab'],['law']],
  [3,1,'Video surveillance','Limit cameras to protect privacy','More cameras in the streets for the sake of security',['privacy'],['auth','law']],
  [3,-1,'Minors','Toughen the law for serious crimes by minors','Keep an educational approach to minors',['law'],['rehab']],
  [3,-1,'Reoffending','More prison time for repeated petty offences, even if the number of prisoners grows','Supervised alternatives to prison, even if punishment is less immediate',['law'],['rehab']],
  [3,-1,'Defence','Increase defence spending, even if other budget items have to be cut','Do not increase it and spend that money on other items',['mil'],['pac']],
  [4,1,'Entry','More legal routes to come and work','Stricter controls and quotas',['imm_pro'],['imm_anti']],
  [4,-1,'Integration','Require integration conditions to be met in order to stay','Support integration with public funding',['assim'],['multi']],
  [4,1,'Regularisation','Regularise those who already live and work here','No general regularisations',['imm_pro'],['imm_anti']],
  [4,-1,'Borders','Priority: stopping irregular arrivals','Priority: rescuing and taking in those who arrive',['imm_anti','law'],['imm_pro','multi']],
  [4,1,'Immigration and the economy','More immigration is needed to fill jobs and sustain pensions','Before bringing in more workers, give jobs to the existing unemployed',['imm_pro'],['imm_anti','nation']],
  [4,-1,'Access to services','Depending on length of residence','Healthcare and education for all residents',['assim','imm_anti'],['multi','welfare']],
  [5,1,'Who decides','More power for the regions (autonomous communities)','More power for the central government',['fed'],['cent']],
  [5,-1,'Funding','The same rules for all regions','Let each region manage more of its own taxes',['cent'],['fed']],
  [5,1,'Languages','More presence of regional official languages in the state','A single state language as the common language of institutions',['lang_min'],['lang_one']],
  [5,-1,'Services in the regions','Coordinated from the centre for the whole country','Let each region organise them in its own way',['cent'],['fed']],
  [5,-1,'Status of territories','The future of a territory is decided by the whole country','Each territory may decide its relationship with the rest',['unity'],['sep']],
  [5,1,'Special status','Recognise more special features for some territories','The same treatment for all territories',['fed'],['cent']],
  [6,1,'Energy transition','Speed it up, even if it costs more in the short term','Go slower, even if emissions take longer to fall',['eco'],['growth']],
  [6,-1,'Environmental rules','Fewer rules, even if nature is less protected','Stricter rules, even if production becomes more expensive',['growth'],['eco']],
  [6,1,'Cars in the city','Restrict the entry of the most polluting cars','No restrictions on traffic by type of car',['eco'],['growth']],
  [6,-1,'Water','Priority: irrigation and farm production','Priority: the health of rivers and aquifers',['agr'],['eco']],
  [6,1,'Pollution','Those who pollute more should pay more tax','No new taxes on pollution',['eco'],['growth']],
  [6,-1,'Natural areas','Make economic projects easier, even if they affect natural areas','Protect more natural areas, even if it limits projects',['growth'],['eco']],
  [7,1,'Decisions','Let the EU decide more things jointly','Let each country take back more decisions',['euro'],['sov']],
  [7,-1,'European defence','Each country with its own defence','A common European defence',['sov'],['euro']],
  [7,1,'European rules','Always apply them, like the other countries','Have the right not to apply those the country considers harmful',['euro'],['sov']],
  [7,-1,'EU budget','Contribute less to the European budget','A larger common budget, including common debt',['sov'],['euro','cosmo']],
  [7,1,'Veto','Decide by majority in the EU, without national vetoes','Keep each country’s right of veto',['euro'],['sov']],
  [7,-1,'Identity','National identity first','Feeling a citizen of Europe as well as of one’s own country',['nation'],['euro','cosmo']]
];
// Шесть вступительных вопросов о системе. a/b — очки вариантов для [одна, доминантная, две, много]
const SYSK=['one','dom','two','multi'];
const SYSN={auto:'Chosen by the test',one:'One-party',dom:'Dominant-party',two:'Two-party',multi:'Multi-party'};
const SYSF={one:'One-party system',dom:'Dominant-party system',two:'Two-party system',multi:'Multi-party system'};
const SYSD={one:'All seats go to a single party: the one closest to your answers.',dom:'The party closest to you immediately gets a majority; the remaining seats are divided by the answers.',two:'Two rival parties share the seats: the one closest to your answers and its main ideological opponent.',multi:'All parties share the seats according to your answers.'};
const SYSQ=[
  {q:'Who leads the country',A:'The country needs a single force that leads it without looking back at opponents',B:'Power should be shared among many forces',a:[2,1,0,0],b:[0,0,1,2]},
  {q:'The opposition',A:'The opposition gets in the way of work and splits society',B:'A strong opposition is necessary, even if it slows decisions down',a:[3,1,0,0],b:[0,0,2,1]},
  {q:'Turnover of power',A:'Let the same people govern as long as they cope: stability matters more',B:'Power should regularly pass from one group to another',a:[0,3,0,0],b:[0,0,2,1]},
  {q:'How many parties',A:'Two clear alternatives are enough: one governs, the other criticises',B:'There should be many parties so that everyone can find their own',a:[0,0,2,0],b:[0,0,0,2]},
  {q:'Government',A:'Single-party government: it is clear who answers for what',B:'Coalitions and compromises: decisions take more opinions into account',a:[2,1,2,0],b:[0,0,0,2]},
  {q:'Whom to vote for',A:'For a party list and its programme',B:'For a specific deputy from one’s own district',a:[0,0,0,1],b:[0,0,1,0]}
];
// Министерские портфели: [код, название, вес поста, черты, из-за которых партия хочет этот портфель]
const PORT=[
  ['pm','Prime Minister',1,[]],
  ['fin','Finance',.8,['tax_hi','tax_lo','mkt','gos']],
  ['for','Foreign Affairs',.7,['euro','sov','west','antiwest','cosmo','eurasia','nation']],
  ['int','Interior',.7,['law','auth','imm_anti','privacy']],
  ['def','Defence',.6,['mil','pac']],
  ['eco','Economy and Industry',.6,['biz','mkt','nat','priv','prot','growth']],
  ['jus','Justice',.5,['rehab','law','lib','plural']],
  ['soc','Labour and Social Protection',.5,['welfare','labor','equal','self']],
  ['hea','Healthcare',.45,['pub','choice','welfare']],
  ['edu','Education and Science',.45,['pub','prog','trad','rel','sec']],
  ['env','Environment and Energy',.4,['eco','growth']],
  ['ter','Regions and Territories',.35,['fed','cent','sep','unity','lang_min','lang_one']],
  ['agr','Agriculture',.3,['agr','prot']],
  ['mig','Migration and Integration',.3,['imm_pro','imm_anti','multi','assim']],
  ['cul','Culture',.25,['trad','prog','soviet','nation','multi']]
];
// ══════ Думские сценарии: выборы в Государственную думу 1993–2026 и скрытый вымышленный сценарий 2026 года (ключ x2026) ══════
// Черты партий, отказы от коалиций и названия союзов — приблизительная редакционная оценка
// по программам и поведению партий в соответствующие годы, не официальные позиции.
const DT=[
  ['Economy and property','Privatisation, taxes, natural resources','#94A8F9','More state','More market'],
  ['Social policy','Pensions, wages, utilities, healthcare','#6DCAAE','More guarantees','More personal responsibility'],
  ['Political system','President, Duma, elections','#EF92B3','More competition','More stability'],
  ['State and order','Crime, defence, media','#9DA4B1','More public oversight','More toughness'],
  ['Regions, nations, migration','Republics, migrants, language','#F9C566','More openness','More control'],
  ['Foreign policy','The West, the CIS, NATO','#77B1E6','Rapprochement with the West','An independent course']
];
// Банк вопросов: [с какого года, по какой год, тема, d, заголовок, A, B, черты A, черты B].
// В сценарий попадают вопросы, чей период включает год выборов.
const DQ=[
  [1993,1999,0,-1,'Privatisation','Continue privatisation: a private owner is more efficient than the state','Stop privatisation and review its results',['priv','mkt'],['nat','gos']],
  [1993,1995,0,-1,'Prices and reforms','Free prices and a tight budget, even if the transition is painful','State price regulation and support for enterprises, even if reforms slow down',['mkt'],['gos','prot']],
  [1993,2003,0,-1,'Land','Allow the free sale and purchase of land','Farmland must not become a commodity',['mkt','priv'],['agr','gos']],
  [1993,1999,0,-1,'IMF loans','Take IMF loans and meet its conditions','Abandon IMF programmes and rely on our own resources',['west','mkt'],['sov','prot']],
  [1999,2007,0,1,'Results of privatisation','Review the privatisation of the 1990s and return major assets to the state','No review: a new redistribution of property is more dangerous than old mistakes',['nat'],['priv','stab']],
  [1999,2027,0,1,'Natural resource industries','Return oil, gas and mineral resources to state ownership','Leave extraction to private companies and tax them',['nat'],['priv','mkt']],
  [2003,2027,0,1,'Income tax','A progressive scale: the higher the income, the higher the rate','A single rate for all incomes',['tax_hi'],['tax_lo']],
  [2007,2027,0,-1,'State corporations','Scale back state corporations and sell their assets','Keep and strengthen the role of state companies in key industries',['priv'],['nat','gos']],
  [1993,2027,0,-1,'Business and inspections','Cut taxes and inspections for business, even if the budget loses revenue','Keep controls and levies to fund state spending',['biz','tax_lo'],['gos']],
  [1999,2011,0,-1,'Joining the WTO','Join the WTO and open the market to competition','Protect domestic producers with tariffs, even if goods cost more',['mkt','west'],['prot']],
  [1993,2027,0,1,'The Soviet experience','The Soviet experience in the economy and social sphere is a foundation worth returning to','The Soviet model has run its course; we must move forward without looking back at it',['soviet'],['mkt','prog']],
  [2007,2027,0,1,'Oil reserves','Spend the accumulated oil revenues on the economy and social sphere now','Save the reserves for a crisis',['welfare','gos'],['stab','self']],
  [2016,2027,0,1,'Sanctions and import substitution','Develop import substitution and answer sanctions with restrictions of our own','Seek the lifting of sanctions and open the market',['prot','sov'],['mkt','west']],

  [1993,1999,1,1,'Wages and pensions','Index wages and pensions to prices, even if it fuels inflation','Bring inflation down first, even if incomes lag behind for a while',['welfare','labor'],['mkt']],
  [1993,1999,1,1,'Lost savings','The state must fully compensate deposits wiped out in the early 1990s','Full compensation is beyond the budget’s means',['welfare','soviet'],['self']],
  [1993,2027,1,1,'Healthcare and education','Free for everyone, paid for by the budget','Develop paid services and insurance schemes alongside free ones',['pub'],['choice']],
  [1993,2027,1,-1,'Labour relations','Make hiring and firing easier so that business creates jobs','Strengthen workers’ protection and the role of trade unions',['biz'],['labor']],
  [1999,2027,1,1,'Utility tariffs','Freeze tariffs and limit their growth by law','Tariffs should cover costs, with subsidies to help the poor',['gos','welfare'],['mkt']],
  [2003,2007,1,1,'Monetisation of benefits','Keep benefits in kind: free transport and medicines','Replace benefits with cash payments',['welfare','soviet'],['mkt','choice']],
  [2003,2016,1,1,'Retirement age','Do not raise the retirement age, even if it is harder for the budget','Raise it gradually to keep the pension system sustainable',['welfare'],['self']],
  [2021,2027,1,1,'Pension reform','Reverse the 2018 increase in the retirement age','Keep the increase: otherwise the pension system will not cope',['welfare'],['self','stab']],
  [2007,2027,1,1,'Support for families','Expand payments to all families with children','Give targeted help only to families in need',['welfare','trad'],['self']],
  [2016,2027,1,1,'Working pensioners','Bring back pension indexation for working pensioners','Do not bring it back: the budget cannot afford it',['welfare'],['self','stab']],

  [1993,2027,2,-1,'President and parliament','A strong presidency: the president forms the government himself','The government should answer to the Duma',['pres'],['parl']],
  [1993,2003,2,-1,'Television','The state has the right to control the main TV channels','Television should be independent of the state',['auth','stab'],['plural','lib']],
  [1993,2003,2,1,'Referendums','Put key questions to a referendum more often','Elected representatives should decide, not plebiscites',['direct','pop'],['stab','tech']],
  [2003,2007,2,-1,'The power vertical','Strengthen the power vertical: the country was poorly governed for too long','Return powers to the regions and parliament',['cent','stab'],['fed','parl']],
  [2003,2027,2,1,'Access to elections','Lower the barriers: the threshold, signature collection, party registration','Keep high barriers: parliament should consist of large parties',['plural'],['stab']],
  [2007,2011,2,1,'Governors','Bring back direct elections of governors','Keep governors appointed on the president’s nomination',['plural','fed'],['cent','stab']],
  [2016,2027,2,1,'Municipal filter','Abolish the municipal filter in gubernatorial elections','Keep the filter: it screens out random candidates',['plural'],['stab']],
  [2007,2027,2,-1,'Rallies','Rallies need official approval to keep order','Peaceful rallies should require only notification, not permission',['auth','stab'],['lib','plural']],
  [2007,2027,2,1,'The “against all” option','Bring back the “against all” option and make referendums easier to hold','Leave things as they are: decisions are made by elected representatives',['direct'],['stab']],
  [2011,2016,2,-1,'Presidential term','Six years: the authorities have time to finish what they started','Four years: the authorities should answer to voters more often',['stab'],['plural']],
  [2021,2021,2,-1,'The 2020 amendments','Resetting presidential terms is justified: the country needs continuity','The terms should not have been reset: power must change hands',['stab','pres'],['plural']],
  [2021,2027,2,-1,'Electronic voting','Expand remote electronic voting','Abandon it: a paper ballot is more reliable',['tech','stab'],['plural']],

  [1993,2027,3,-1,'Fighting corruption','Emphasis on harsh punishment and confiscation of property','Emphasis on transparency, independent courts and public oversight',['law','auth'],['plural']],
  [1993,2007,3,-1,'Crime','Emergency measures against crime, even at the cost of restricting rights','Fight it only within the law and under court supervision',['law','auth'],['lib','rehab']],
  [2011,2027,3,-1,'Police','More powers and money for the police','More public oversight of the police',['law','auth'],['plural','privacy']],
  [1993,2027,3,-1,'Defence spending','Increase spending on defence and rearmament','Spend that money on education and healthcare',['mil'],['pac']],
  [1999,2003,3,-1,'Chechnya','Restore control over Chechnya by military force','Seek a political solution through negotiations',['unity','mil'],['pac']],
  [2011,2027,3,-1,'Internet and media','The state should restrict harmful information','The internet and media should be free of censorship',['auth'],['lib','privacy']],
  [2016,2027,3,-1,'Foreign agents','The foreign agents law protects the country from outside interference','This law restricts civil society and should be repealed',['sov','auth'],['lib','plural']],

  [1993,2003,4,1,'Regions and the centre','More autonomy for the regions and republics','A strong centre and uniform rules for all regions',['fed'],['cent','unity']],
  [1993,2027,4,1,'Structure of the federation','Keep the national republics and their special status','Move to territories of equal status with no ethnic basis',['fed','multi'],['lang_one']],
  [1993,2027,4,1,'Compatriots abroad','Do not interfere in the affairs of neighbouring states','Actively protect Russians and Russian speakers abroad, including simplified citizenship',['cosmo','west'],['nation','eurasia']],
  [2003,2027,4,-1,'Labour migration','Introduce visas with Central Asian countries and reduce the number of labour migrants','Keep visa-free entry: the economy needs workers',['imm_anti'],['imm_pro']],
  [2003,2016,4,-1,'The Russian people in the Constitution','Enshrine a special role for the Russian people in the Constitution','Keep the formula of a multinational people without singling anyone out',['nation'],['multi']],
  [2007,2011,4,-1,'Exams for migrants','A compulsory exam in Russian language and history to work in Russia','Do not complicate hiring with extra exams',['assim'],['imm_pro','biz']],
  [2016,2027,4,-1,'Languages of the republics','Languages of the republics in schools only at parents’ request','Republics have the right to make their languages compulsory in schools',['lang_one'],['lang_min','fed']],

  [1993,1995,5,-1,'Collapse of the USSR','Work towards a new union of the former Soviet republics','Accept the collapse and build relations with neighbours as with independent countries',['soviet','eurasia'],['west','cosmo']],
  [1995,2003,5,-1,'Union with Belarus','Speed up unification with Belarus into a union state','No rush: unification is costly and will slow reforms',['eurasia'],['mkt','west']],
  [1993,2027,5,1,'Relations with the West','Move closer to the USA and Europe and join Western institutions','Defend our interests more firmly, even at the cost of cooler relations',['west'],['antiwest','sov']],
  [1995,2027,5,1,'NATO','Cooperate with NATO where interests coincide','Treat NATO enlargement as a threat and respond to it',['west','cosmo'],['antiwest','mil']],
  [1995,1999,5,1,'The START II treaty','Ratify the treaty and cut nuclear arsenals','Do not ratify: the nuclear shield is the guarantee of security',['west','pac'],['mil','antiwest']],
  [1999,1999,5,-1,'Yugoslavia','Help Yugoslavia against NATO, up to and including arms supplies','Condemn the bombing but stay out of the conflict',['antiwest'],['pac','west']],
  [2003,2027,5,-1,'Where to integrate','Priority: unions with CIS neighbours — the Customs Union, the Eurasian Union','Priority: the European path and closer ties with the EU',['eurasia'],['euro','west']],
  [2016,2027,5,-1,'Crimea','The annexation of Crimea was the right step, even at the cost of sanctions','That step violated international law and isolated the country',['nation','sov','antiwest'],['west','cosmo']],
  [2016,2021,5,-1,'Operation in Syria','The military operation in Syria protects Russia’s interests','That money is needed more at home',['mil','antiwest'],['pac']],
  [1995,2027,0,-1,'Natural monopolies','Break up and privatise the natural monopolies: gas, railways, power','Keep them unified and state-owned',['priv','mkt'],['nat','gos']],
  [1993,2027,0,1,'Support for agriculture','Increase state support for agriculture: subsidies, procurement, cheap loans','Agriculture should earn its own keep: subsidies distort the market',['agr','prot'],['mkt']],
  [1993,2003,0,1,'Capital and currency','Restrict capital outflow and the circulation of the dollar','Free movement of capital and a convertible rouble',['gos','sov'],['mkt','west']],
  [1993,2027,0,-1,'Foreign investors','Admit foreign companies more widely, including to natural resources','Strategic industries are for domestic capital only',['mkt','west'],['sov','prot']],
  [1993,2027,0,1,'The budget','A budget deficit is acceptable for the sake of wages and social spending','The budget must be balanced, even at the cost of spending cuts',['welfare','gos'],['self','tax_lo']],
  [1993,1995,0,-1,'Vouchers','Voucher privatisation gave people a share in property','The vouchers lost their value: privatisation should have been done differently',['priv'],['nat','welfare']],
  [2003,2027,0,1,'Petrol and food prices','The state should regulate prices for petrol and basic foods','The market sets prices, and the state helps only the poor',['gos','pop'],['mkt']],
  [2007,2027,0,1,'National projects','Large state programmes are the main engine of development','Better to cut taxes and let business develop by itself',['gos','growth','stab'],['tax_lo','biz','mkt']],
  [2011,2027,0,1,'Luxury tax','Introduce a tax on luxury and very high incomes','Do not introduce it: such taxes drive capital out of the country',['tax_hi','equal'],['tax_lo','biz']],
  [1993,2027,0,1,'Ecology and factories','Close harmful plants, even at the cost of jobs','Jobs matter more: environmental requirements can be relaxed',['eco'],['growth','labor']],
  [2016,2016,0,-1,'The “Platon” toll system','Abolish the “Platon” toll for long-haul truckers','Keep it: heavy trucks should pay for road wear',['pop','biz','labor'],['stab','gos']],
  [2021,2027,0,-1,'VAT','Bring VAT back down from 20 to 18 per cent','Keep 20 per cent: the budget needs the money',['tax_lo','biz','pop'],['stab']],

  [1993,2027,1,1,'Minimum wage','Raise the minimum wage to the subsistence level and above, even if it is hard on business','Raise it only in step with economic growth',['labor','welfare'],['biz','mkt']],
  [1993,2027,1,1,'Housing','The state should build housing and give it free to those in need','People buy housing themselves, and the state helps with mortgages',['welfare','soviet','gos'],['mkt','self']],
  [1999,2027,1,1,'Higher education','Free for everyone who passes the competitive entry','Paid tuition and student loans are normal practice',['pub','equal'],['choice','self']],
  [2003,2027,1,1,'Unified State Exam','Abolish the Unified State Exam and bring back traditional exams','Keep the Unified State Exam as a single exam for everyone',['soviet'],['tech','stab']],
  [2007,2027,1,1,'Medicine prices','The state should strictly cap medicine prices','Price caps drive medicines off the market',['gos','welfare'],['mkt']],
  [2007,2027,1,1,'Alcohol and tobacco','Tighten restrictions on alcohol and tobacco','Adults decide for themselves what to drink and smoke',['trad','auth'],['lib']],
  [1995,1999,1,1,'Wage arrears','Make managers criminally liable for delayed wages','Punishment will not help: enterprises have nothing to pay with; reforms are needed',['labor','law'],['mkt','biz']],
  [1995,1995,1,1,'Financial pyramids','The state should return the money of defrauded pyramid-scheme investors','The state is not responsible for private scams',['welfare','pop'],['self','mkt']],
  [2007,2016,1,-1,'The Olympics and championships','The Olympics and the World Cup are worth the money: they are the country’s prestige','That money is needed more by hospitals and roads',['stab','nation','growth'],['welfare','pub']],
  [2016,2016,1,1,'Capital repair contributions','Abolish contributions for major housing repairs','Keep the contributions: otherwise there is no one to repair the buildings',['welfare','pop'],['stab','self']],
  [2021,2027,1,-1,'Waste reform','Build waste incinerators and new landfills','Bet on separate collection and recycling',['growth','stab'],['eco']],

  [1995,2027,2,1,'The Federation Council','Elect senators by direct vote','Keep senators appointed by the regions',['plural','direct'],['stab']],
  [1993,2027,2,1,'Recall of deputies','Voters should have the right to recall their deputy','A deputy should serve the full term without the threat of recall',['direct','pop'],['stab']],
  [1993,2027,2,1,'The Soviet past','Give an official legal assessment of the crimes of the Soviet regime','The Soviet past is a part of history to be proud of',['lib','plural'],['soviet']],
  [1999,1999,2,1,'Impeachment','The Duma was right to try to remove Yeltsin from office','Impeachment would only have destabilised the country',['parl','soviet'],['pres','stab']],
  [2007,2007,2,-1,'After 2008','Vladimir Putin should stay in power after 2008','The president should leave after two terms, as the Constitution requires',['stab','pres'],['plural','parl']],
  [2011,2011,2,-1,'The job swap','Swapping posts within the tandem is a normal decision','The question of power cannot be settled by a deal between two people',['stab'],['plural']],
  [1995,2027,2,1,'City mayors','City mayors should be elected by residents','Mayors can be appointed: it makes government more efficient',['plural','fed','direct'],['cent','stab']],
  [1993,2027,2,1,'Courts','Introduce elected judges and expand jury trials','Judges should be appointed by the president: it makes the courts more professional',['plural','direct','lib'],['pres','stab']],
  [2011,2027,2,1,'Election observers','Expand the rights of independent observers and put cameras in polling stations','The current guarantees of fair elections are sufficient',['plural'],['stab']],
  [2021,2027,2,1,'Three-day voting','Voting should take place on a single day','Three-day voting is more convenient for voters',['plural'],['stab','tech']],

  [1995,1995,3,-1,'The war in Chechnya','Sending troops into Chechnya was necessary to hold the country together','The war must be stopped and negotiations held',['pres','auth'],['pac','parl']],
  [1999,2027,3,-1,'Security services','Expand the powers of the security services for the sake of security','Strengthen parliamentary and judicial oversight of the security services',['auth','law'],['plural','privacy','parl']],
  [1993,2027,3,-1,'Church and state','The state should support the traditional religions','The church should be fully separated from the state and schools',['rel','trad'],['sec']],
  [2011,2027,3,-1,'Traditional values','The law should protect the traditional family and values','The state should not interfere in private life',['trad','rel'],['lib','privacy']],
  [1993,2027,3,1,'Amnesty','Soften punishment for non-violent crimes and use amnesties more widely','Punishment must be inevitable: amnesties do harm',['rehab','lib'],['law']],
  [2003,2007,3,-1,'The Yukos case','The Yukos case is lawful punishment for tax evasion','The Yukos case is selective justice and a bad signal to business',['stab','law','pop'],['lib','biz','plural']],
  [2007,2027,3,-1,'Extremism laws','Extremism laws are needed to protect society','These laws are too vague and should be narrowed',['auth','stab'],['lib','plural']],

  [2003,2027,4,-1,'Merging regions','Enlarge regions by merging small ones','Keep the current regional borders',['cent','tech'],['fed','multi']],
  [1993,2027,4,1,'Regional taxes','Leave most of the taxes collected to the regions','Collect taxes centrally and redistribute them between regions',['fed'],['cent','equal']],
  [1993,2027,4,1,'Citizenship','Make citizenship easier for everyone who wants to live and work in Russia','Citizenship only after long residence, exams and vetting',['imm_pro','cosmo'],['imm_anti','assim']],
  [2003,2027,4,1,'Illegal migration','Legalise migrants who already work in the country','Deport illegal migrants and punish employers',['imm_pro','biz'],['imm_anti','law']],
  [1993,2027,4,-1,'The Russian language','The Russian language and culture should have priority across the whole country','The languages and cultures of Russia’s peoples should be supported on equal terms',['lang_one','nation'],['lang_min','multi']],

  [1993,2027,5,1,'The Kuril Islands','For the sake of a peace treaty with Japan, the fate of the southern Kurils can be discussed','The Kurils are not up for bargaining',['west','cosmo'],['nation','sov','unity']],
  [2003,2027,5,-1,'China or Europe','Russia’s main partner is China and the countries of Asia','Russia’s main partner is Europe',['antiwest','eurasia'],['euro','west']],
  [1995,2021,5,1,'The Council of Europe','Stay in the Council of Europe and comply with the European Court’s rulings','Rulings of international courts must not stand above the Constitution',['west','euro','lib'],['sov']],
  [2011,2016,5,-1,'Abkhazia and South Ossetia','Recognising Abkhazia and South Ossetia was right','Recognition damaged relations with the world and achieved little',['nation','sov','antiwest'],['west','cosmo']],
  [1993,2027,5,1,'Aid to other countries','Write off debts and help allies for the sake of influence in the world','Solve problems at home first',['eurasia','cosmo'],['pop','nation']],
  [2016,2016,5,-1,'The adoption ban','The ban on Americans adopting Russian orphans is justified','The ban punishes orphans and should be lifted',['antiwest','sov','nation'],['west','lib','cosmo']],
  [2027,2027,2,1,'Transfer of power','The new leadership should be decided by competitive elections open to all candidates','Continuity matters more: an agreed successor should carry on the course',['plural'],['stab','pres']],
  [2027,2027,2,1,'Political prisoners','Release those convicted on political charges and review their cases','The sentences were lawful, there are no grounds to review them',['lib','rehab','plural'],['law','auth']],
  [2027,2027,2,1,'Presidential powers','Cut the president’s powers and restore the two-term limit with no exceptions','The country needs a strong presidency even after the change of leader',['parl','plural'],['pres','stab']],
  [2027,2027,2,1,'The returning opposition','Let politicians who returned from exile or were released from prison stand in elections','Bar those who called for sanctions against the country',['plural','lib'],['sov','auth']],
  [2027,2027,2,1,'Vetting of officials','Officials and security officers of the former leadership should be vetted and leave if they broke the law','No purges: the country needs accord, not score-settling',['plural','lib'],['stab','unity']],
  [2026,2027,5,1,'The fighting in Ukraine','Seek peace as soon as possible, even at the cost of concessions','Continue until the stated goals are achieved',['pac','west'],['mil','nation','antiwest']],
  [2026,2027,5,1,'Territories incorporated in 2022','Their status can be a subject of negotiation','Their status is not up for discussion',['west','cosmo','pac'],['nation','sov','unity']],
  [2026,2027,3,-1,'Conscription and mobilisation','Keep conscription and the option of mobilisation','Switch to a fully professional army',['mil'],['pac','lib']],
  [2026,2027,1,1,'Combat veterans','Lifelong benefits, university quotas and priority in the civil service','Support is needed, but without special privileges over other citizens',['mil','welfare','nation'],['equal']],
  [2026,2027,0,-1,'Foreign companies that left','Bring foreign companies back and let them buy back their former assets','Do not bring them back: domestic owners have taken their place',['mkt','west'],['prot','sov']],
  [2026,2027,0,1,'Review of privatisation','Return to the state the enterprises that were privatised unlawfully','Lock in the results of privatisation and protect owners',['nat','gos'],['priv','biz']]
];
// Базовые наборы черт для партий, которые участвовали во многих выборах; tr() подправляет их под конкретный год
const tr=(base,over)=>Object.assign({},base,over||{});
const B_KPRF={gos:3,nat:3,tax_hi:3,labor:3,welfare:3,pub:3,equal:3,soviet:3,prot:2,agr:1,parl:3,plural:2,direct:2,mil:3,sov:3,antiwest:3,eurasia:3,trad:2,law:2,unity:2,nation:1,imm_anti:1,cent:1};
const B_LDPR={nation:3,imm_anti:3,assim:2,cent:3,unity:3,lang_one:3,auth:2,pres:3,law:3,mil:3,pop:3,antiwest:2,sov:3,gos:2,welfare:2,prot:2,plural:1,eurasia:2};
const B_YAB={plural:3,parl:3,lib:3,privacy:3,west:3,euro:2,mkt:2,biz:2,welfare:2,pub:1,eco:3,rehab:3,pac:2,fed:3,sec:1,prog:2,direct:1,equal:1,imm_pro:1,multi:2,cosmo:2};
const B_ER={stab:3,pres:3,cent:3,unity:3,auth:1,law:2,mkt:1,gos:2,nat:2,tax_lo:2,welfare:2,trad:2,rel:1,mil:2,sov:1,antiwest:1,eurasia:2,growth:2,tech:1,multi:1};
const B_SR={gos:2,tax_hi:3,labor:3,welfare:3,pub:3,equal:3,nat:1,parl:1,plural:2,direct:1,prog:1,sov:1,eurasia:1,law:1,mil:1};
const B_SPS={mkt:3,priv:3,biz:3,tax_lo:3,self:2,choice:2,west:3,lib:3,plural:3,prog:2,fed:2,cosmo:1,imm_pro:1};
const B_APR={agr:3,gos:3,prot:3,welfare:2,soviet:2,nat:2,labor:2,trad:2,parl:2,sov:2,eurasia:2,antiwest:1,tax_hi:1};
const B_ROST={mkt:3,biz:3,priv:2,tax_lo:3,self:1,choice:2,tech:2,plural:1,lib:1,growth:2,imm_pro:1};
const CK='#C8102E', CL='#E3B505', CY='#2E9E4F', CE='#0C4DA2', CS='#E8730C', CR='#1FA3B5', CA='#7A8B2A';
// F — партии слева направо; no — пары, которые не войдут в одну коалицию; co — названия союзов
const DUMA={
  1993:{thr:5,sys:'mixed',note:'The first Duma after the events of October 1993',
    F:[
      ['CPRF',CK,'The restored Communist Party: against privatisation and the course of reforms. Party-list vote: 12.4%.',B_KPRF],
      ['Agrarian Party',CA,'The party of collective farms and the agro-industrial sector: against the sale of land, for state support of agriculture. Party-list vote: 8.0%.',B_APR],
      ['Women of Russia','#D45BA0','A centrist bloc: social protection, the family, against the use of force. Party-list vote: 8.1%.',{welfare:3,pub:3,equal:2,labor:2,pac:3,gos:1,prog:1,stab:1,trad:1}],
      ['DPR',  '#5C6B7A','Nikolai Travkin’s Democratic Party of Russia: moderate reforms and the unity of the country. Party-list vote: 5.5%.',{mkt:1,biz:2,gos:1,unity:2,cent:1,nation:1,parl:2,plural:2,prot:2,trad:1,sov:1,welfare:1}],
      ['Yabloko',CY,'The democratic opposition to Gaidar’s reforms: a market without shock therapy, against the new Constitution. Party-list vote: 7.9%.',B_YAB],
      ['PRES','#7B5EA7','Sergei Shakhrai’s Party of Russian Unity and Accord: federalism and moderate reforms. Party-list vote: 6.7%.',{fed:3,mkt:2,priv:1,stab:2,pres:2,biz:1,multi:2,welfare:1,west:1,tech:1}],
      ['Russia’s Choice',CR,'Yegor Gaidar’s bloc, the president’s mainstay: privatisation, free prices, a pro-Western course. Party-list vote: 15.5%.',{mkt:3,priv:3,biz:3,tax_lo:2,self:2,choice:2,west:3,pres:3,lib:2,plural:2,cosmo:2,fed:1,prog:2}],
      ['LDPR',CL,'Vladimir Zhirinovsky’s party, the party-list winner: nationalism and the restoration of a great power. Party-list vote: 22.9%.',tr(B_LDPR,{eurasia:3})]
    ],
    no:[['CPRF','Russia’s Choice'],['LDPR','Russia’s Choice'],['LDPR','Yabloko'],['Agrarian Party','Russia’s Choice'],['CPRF','Yabloko']],
    co:[['Left opposition',['CPRF','Agrarian Party']],['People’s Patriotic Bloc',['CPRF','Agrarian Party','LDPR']],['Coalition of reforms',['Russia’s Choice','PRES','Yabloko']],
      ['Centrist bloc',['Women of Russia','DPR','PRES']],['Broad centre',['Russia’s Choice','PRES','Women of Russia','DPR']],['Presidential majority',['Russia’s Choice','PRES']]]},
  1995:{thr:5,sys:'mixed',note:'Victory of the left opposition on the eve of the presidential election',
    F:[
      ['CPRF',CK,'The main opposition force and the winner of the election. Party-list vote: 22.3%.',B_KPRF],
      ['Agrarian Party',CA,'The communists’ ally in the countryside; it missed the threshold but won district seats. Party-list vote: 3.8%.',B_APR],
      ['Women of Russia','#D45BA0','A centrist social bloc that fell just short of the threshold. Party-list vote: 4.6%.',{welfare:3,pub:3,equal:2,labor:2,pac:3,gos:1,prog:1,stab:1,trad:1}],
      ['Yabloko',CY,'Grigory Yavlinsky’s democratic opposition: against the war in Chechnya and the government’s course. Party-list vote: 6.9%.',B_YAB],
      ['Democratic Choice of Russia','#19B5A5','Yegor Gaidar’s “Democratic Choice of Russia”: continued reforms, against the Chechen war. Party-list vote: 3.9%.',tr(B_SPS,{pac:1,pres:1,cosmo:2,tax_lo:2})],
      ['Our Home — Russia','#3565B5','Prime Minister Viktor Chernomyrdin’s party of power: stability and moderate reforms. Party-list vote: 10.1%.',{stab:3,pres:3,mkt:2,priv:2,gos:1,biz:1,west:2,unity:2,cent:1,tech:2,growth:2,welfare:1,law:1,mil:1}],
      ['LDPR',CL,'Zhirinovsky’s party: nationalism, strict order, support for a strong presidency. Party-list vote: 11.2%.',tr(B_LDPR,{eurasia:3})]
    ],
    no:[['CPRF','Democratic Choice of Russia'],['LDPR','Democratic Choice of Russia'],['LDPR','Yabloko'],['Agrarian Party','Democratic Choice of Russia'],['CPRF','Our Home — Russia'],['CPRF','Yabloko']],
    co:[['People’s Patriotic Union',['CPRF','Agrarian Party']],['Left majority',['CPRF','Agrarian Party','Women of Russia']],['Government bloc',['Our Home — Russia','Democratic Choice of Russia']],
      ['Coalition of reformers',['Our Home — Russia','Democratic Choice of Russia','Yabloko']],['Democratic opposition',['Yabloko','Democratic Choice of Russia']],['Great-power bloc',['Our Home — Russia','LDPR']]]},
  1999:{thr:5,sys:'mixed',note:'“Unity” against “Fatherland” amid the second Chechen campaign',
    F:[
      ['CPRF',CK,'First place on party lists: the left opposition to the outgoing president. Party-list vote: 24.3%.',B_KPRF],
      ['Fatherland — All Russia','#B8651B','The bloc of Primakov and Luzhkov: governors, state regulation, a stronger parliament. Party-list vote: 13.3%.',{gos:2,fed:2,cent:1,stab:2,welfare:2,prot:2,parl:2,nat:1,unity:2,eurasia:2,sov:2,antiwest:1,mil:2,biz:1,tech:1,trad:1}],
      ['Yabloko',CY,'The democratic opposition: for negotiations in Chechnya and against the oligarchs. Party-list vote: 5.9%.',B_YAB],
      ['Union of Right Forces',CR,'The bloc of Kiriyenko, Nemtsov and Khakamada: liberal reforms and support for the new prime minister. Party-list vote: 8.5%.',tr(B_SPS,{pres:1,unity:1,lib:2,plural:2,fed:1})],
      ['Unity',CE,'The “Bear” bloc created in support of Vladimir Putin: order and the unity of the country. Party-list vote: 23.3%.',{stab:2,pres:3,unity:3,cent:2,law:2,mil:3,mkt:1,gos:1,auth:1,nation:1,tax_lo:1,trad:1,welfare:1}],
      ['Zhirinovsky Bloc',CL,'The LDPR under another name after its list was denied registration. Party-list vote: 6.0%.',B_LDPR]
    ],
    no:[['CPRF','Union of Right Forces'],['Zhirinovsky Bloc','Yabloko'],['CPRF','Yabloko']],
    co:[['The package deal',['CPRF','Unity']],['Pro-Putin majority',['Unity','Union of Right Forces','Zhirinovsky Bloc']],['Right-wing coalition',['Unity','Union of Right Forces']],
      ['Unity and Fatherland',['Unity','Fatherland — All Russia']],['Centre-left bloc',['CPRF','Fatherland — All Russia']],['Democratic coalition',['Yabloko','Union of Right Forces']]]},
  2003:{thr:5,sys:'mixed',note:'“United Russia” wins a constitutional majority',
    F:[
      ['CPRF',CK,'The left opposition, which lost half of its votes. Party-list vote: 12.6%.',B_KPRF],
      ['Agrarian Party',CA,'The party of the countryside: support for the agro-industrial sector and limits on land sales. Party-list vote: 3.6%.',tr(B_APR,{soviet:1})],
      ['Rodina','#8B1E3F','The bloc of Glazyev and Rogozin: natural resource rents for the people, protection of compatriots. Party-list vote: 9.0%.',{nation:3,gos:3,nat:3,tax_hi:2,welfare:2,labor:1,sov:3,antiwest:2,eurasia:3,unity:2,mil:2,prot:2,trad:2,pop:2,imm_anti:2,law:2,plural:1}],
      ['Yabloko',CY,'The democratic opposition, which missed the threshold for the first time. Party-list vote: 4.3%.',B_YAB],
      ['United Russia',CE,'The merged party of power: support for the president and the vertical of government. Party-list vote: 37.6%.',tr(B_ER,{nat:1,mkt:2,antiwest:0,west:1})],
      ['Union of Right Forces',CR,'Liberal reformers, who missed the threshold for the first time. Party-list vote: 4.0%.',tr(B_SPS,{parl:1,euro:1})],
      ['LDPR',CL,'Zhirinovsky’s party: nationalism and support for the president’s course. Party-list vote: 11.5%.',B_LDPR]
    ],
    no:[['CPRF','Union of Right Forces'],['CPRF','United Russia'],['LDPR','Yabloko'],['LDPR','Union of Right Forces'],['Rodina','Union of Right Forces'],['CPRF','Yabloko']],
    co:[['Constitutional majority',['United Russia','LDPR','Rodina']],['Pro-government majority',['United Russia','LDPR']],['Patriotic bloc',['United Russia','Rodina']],
      ['Left-patriotic opposition',['CPRF','Rodina','Agrarian Party']],['United democrats',['Yabloko','Union of Right Forces']],['Centre-right coalition',['United Russia','Union of Right Forces']]]},
  2007:{thr:7,sys:'prop',note:'The first election by party lists only, with a 7% threshold',
    F:[
      ['CPRF',CK,'The main opposition party in the Duma. Party-list vote: 11.6%.',B_KPRF],
      ['Agrarian Party',CA,'The party of the countryside, close to the authorities; it missed the threshold. Party-list vote: 2.3%.',{agr:3,gos:2,prot:3,welfare:2,trad:2,stab:1,sov:1,labor:1}],
      ['A Just Russia',CS,'Sergei Mironov’s new centre-left party: social spending and support for the president. Party-list vote: 7.7%.',tr(B_SR,{stab:1})],
      ['Yabloko',CY,'The democratic opposition outside parliament. Party-list vote: 1.6%.',B_YAB],
      ['United Russia',CE,'Vladimir Putin headed the list; the party won a constitutional majority. Party-list vote: 64.3%.',B_ER],
      ['Union of Right Forces',CR,'Liberals who moved into hard opposition. Party-list vote: 1.0%.',tr(B_SPS,{parl:1,euro:1})],
      ['LDPR',CL,'Zhirinovsky’s party: nationalism and loyalty to the Kremlin. Party-list vote: 8.1%.',B_LDPR]
    ],
    no:[['CPRF','United Russia'],['CPRF','Union of Right Forces'],['Yabloko','United Russia'],['Union of Right Forces','United Russia'],['LDPR','Yabloko'],['LDPR','Union of Right Forces'],['CPRF','Yabloko']],
    co:[['Putin’s Plan',['United Russia','A Just Russia']],['Pro-government majority',['United Russia','LDPR']],['Constitutional majority',['United Russia','A Just Russia','LDPR']],
      ['Left turn',['CPRF','A Just Russia']],['Left bloc',['CPRF','A Just Russia','Agrarian Party']],['United democrats',['Yabloko','Union of Right Forces']]]},
  2011:{thr:7,sys:'prop',note:'The election followed by the Bolotnaya Square protests',
    F:[
      ['CPRF',CK,'Nationalisation of key industries, Soviet-style social guarantees, confrontation with the West. Party-list vote: 19.2%.',B_KPRF],
      ['Patriots of Russia','#8B1E3F','A left-patriotic programme: a state-run economy, a strong army. Party-list vote: 1.0%.',{gos:3,nat:3,welfare:3,labor:2,tax_hi:2,pub:2,soviet:2,prot:3,mil:3,sov:3,antiwest:2,eurasia:2,trad:2,nation:2,unity:2,law:2,plural:1}],
      ['A Just Russia',CS,'A social-democratic programme: progressive tax, protection of labour; it ran against “United Russia”. Party-list vote: 13.2%.',tr(B_SR,{parl:2})],
      ['Yabloko',CY,'Social liberalism: political freedoms, the European path, ecology. Party-list vote: 3.4%.',B_YAB],
      ['United Russia',CE,'The party of power: stability, the vertical of government, state companies. It lost its constitutional majority. Party-list vote: 49.3%.',B_ER],
      ['Right Cause',CR,'Right-wing liberalism: low taxes, privatisation, freedom of enterprise. Party-list vote: 0.6%.',{mkt:3,biz:3,priv:3,tax_lo:3,self:2,choice:2,west:2,euro:1,plural:2,lib:2,fed:2,tech:1,imm_pro:2,prog:1,privacy:1}],
      ['LDPR',CL,'Nationalism and populism: a tough migration policy, a unitary state. Party-list vote: 11.7%.',tr(B_LDPR,{pres:2})]
    ],
    no:[['CPRF','United Russia'],['Yabloko','United Russia'],['Yabloko','LDPR'],['CPRF','Right Cause'],['A Just Russia','United Russia'],['LDPR','Right Cause'],['CPRF','Yabloko']],
    co:[['Left majority',['CPRF','A Just Russia']],['Left-patriotic bloc',['CPRF','A Just Russia','Patriots of Russia']],['Pro-government majority',['United Russia','LDPR']],
      ['Opposition coalition',['CPRF','A Just Russia','LDPR']],['Liberal bloc',['Yabloko','Right Cause']],['Modernisation coalition',['United Russia','Right Cause']]]},
  2016:{thr:5,sys:'mixed',note:'The return of single-member districts and the “Crimean consensus”',
    F:[
      ['CPRF',CK,'The left opposition, which backed the president’s foreign policy. Party-list vote: 13.3%.',tr(B_KPRF,{nation:2})],
      ['A Just Russia',CS,'A social programme and support for the foreign-policy course. Party-list vote: 6.2%.',tr(B_SR,{plural:1,sov:2,antiwest:1,nation:1})],
      ['Yabloko',CY,'The democratic opposition: against the annexation of Crimea and for closer ties with Europe. Party-list vote: 2.0%.',B_YAB],
      ['Party of Growth','#5B4BB5','The party of business ombudsman Boris Titov: tax breaks and freedom of enterprise. Party-list vote: 1.3%.',B_ROST],
      ['United Russia',CE,'The party of power, which won a record 343 seats. Party-list vote: 54.2%.',tr(B_ER,{antiwest:2,sov:2,nation:1,trad:3})],
      ['Rodina','#8B1E3F','Loyal national patriots; one district seat. Party-list vote: 1.5%.',{nation:3,sov:3,antiwest:3,mil:3,trad:3,gos:2,prot:3,stab:2,pres:2,eurasia:2,unity:2,law:2,welfare:1,imm_anti:2}],
      ['LDPR',CL,'Zhirinovsky’s party: nationalism and support for the foreign policy. Party-list vote: 13.1%.',B_LDPR]
    ],
    cap:[['Rodina','United Russia']],
    no:[['Yabloko','United Russia'],['Yabloko','LDPR'],['Yabloko','Rodina'],['CPRF','Party of Growth'],['CPRF','Yabloko']],
    co:[['Crimean consensus',['United Russia','LDPR','CPRF','A Just Russia']],['Pro-government majority',['United Russia','LDPR']],['Patriotic bloc',['United Russia','Rodina','LDPR']],
      ['Left bloc',['CPRF','A Just Russia']],['The party of power and business',['United Russia','Party of Growth']],['Liberal bloc',['Yabloko','Party of Growth']]]},
  2021:{thr:5,sys:'mixed',note:'A fifth party enters the Duma for the first time in many years',
    F:[
      ['CPRF',CK,'The main opposition party: against the pension reform and electronic voting. Party-list vote: 18.9%.',tr(B_KPRF,{nation:2})],
      ['A Just Russia — For Truth',CS,'A merger with the parties of Prilepin and Semigin: a social and patriotic agenda. Party-list vote: 7.5%.',tr(B_SR,{plural:1,stab:1,pres:1,sov:2,antiwest:2,nation:2,mil:2,trad:1})],
      ['Yabloko',CY,'The democratic opposition outside the Duma. Party-list vote: 1.3%.',B_YAB],
      ['New People','#19B5A5','A new party of entrepreneurs: small business, digitalisation, more rights for the regions. Party-list vote: 5.3%.',{mkt:2,biz:3,tax_lo:2,tech:3,plural:1,lib:1,fed:2,prog:1,choice:1,growth:2,direct:1,welfare:1,stab:1}],
      ['United Russia',CE,'The party of power, which kept its constitutional majority. Party-list vote: 49.8%.',tr(B_ER,{antiwest:2,sov:3,nation:1,trad:3})],
      ['Party of Growth','#5B4BB5','Boris Titov’s party: the interests of business; one district seat. Party-list vote: 0.5%.',B_ROST],
      ['LDPR',CL,'The party’s last election with Vladimir Zhirinovsky at its head. Party-list vote: 7.6%.',B_LDPR]
    ],
    no:[['Yabloko','United Russia'],['Yabloko','LDPR'],['CPRF','United Russia'],['CPRF','Party of Growth'],['CPRF','Yabloko']],
    co:[['Pro-government majority',['United Russia','LDPR']],['Grand loyal coalition',['United Russia','LDPR','A Just Russia — For Truth','New People']],['Renewed centre',['United Russia','New People']],
      ['Patriotic bloc',['United Russia','A Just Russia — For Truth','LDPR']],['Left bloc',['CPRF','A Just Russia — For Truth']],['Coalition of change',['CPRF','A Just Russia — For Truth','New People']],['Liberal bloc',['Yabloko','New People','Party of Growth']]]},
  2026:{thr:5,sys:'mixed',note:'The election of 18–20 September 2026: United Russia wins 349 of 450 seats',
    gate:['Yabloko','In reality the Central Election Commission registered Yabloko’s list on 29 July 2026, and on 10 August the Supreme Court cancelled the registration on a claim by the Rodina party; the appeal was dismissed.'],
    F:[
      ['Communists of Russia','#A01C1C','A small communist party, a rival of the CPRF on the left. Party-list vote: 0.8%.',{soviet:3,gos:3,nat:3,tax_hi:3,labor:3,welfare:3,equal:3,antiwest:3,sov:2,mil:2,auth:2,law:2,eurasia:2,stab:1}],
      ['CPRF',CK,'The second party in the Duma, having lost almost a third of its vote compared with 2021. Party-list vote: 13.5%.',tr(B_KPRF,{nation:2})],
      ['A Just Russia',CS,'A social and patriotic agenda; barely cleared the threshold. Party-list vote: 5.3%.',tr(B_SR,{plural:1,stab:1,pres:1,sov:2,antiwest:2,nation:2,mil:2,trad:1})],
      ['Party of Pensioners','#B8477A','Pensions, benefits and prices; does not challenge the authorities. Party-list vote: 1.9%.',{welfare:3,pub:2,gos:2,equal:2,stab:2,soviet:1,trad:1,pres:1,labor:1}],
      ['Yabloko',CY,'The democratic opposition: peace, human rights, a parliamentary republic. The party’s list was removed from the election before voting.',tr(B_YAB,{pac:3})],
      ['The Greens','#3E8E41','An environmental party without sharp criticism of the authorities. Party-list vote: 1.1%.',{eco:3,welfare:2,stab:2,pub:1,tech:1,gos:1,trad:1,pres:1}],
      ['New People','#19B5A5','The fourth party in the Duma: entrepreneurs, cities, digitalisation. Party-list vote: 7.8%.',{mkt:2,biz:3,tax_lo:2,tech:3,plural:1,lib:1,fed:2,prog:1,choice:1,growth:2,direct:1,welfare:1,stab:1}],
      ['United Russia',CE,'The party of power with a constitutional majority: 349 of 450 seats. Party-list vote: 58.2%.',tr(B_ER,{antiwest:3,sov:3,nation:2,trad:3,mil:3})],
      ['Rodina','#8B1E3F','Loyal national patriots; one district seat, held by Alexei Zhuravlyov. Party-list vote: 0.7%.',{nation:3,sov:3,antiwest:3,mil:3,trad:3,gos:2,prot:3,stab:2,pres:2,eurasia:2,unity:2,law:2,welfare:1,imm_anti:2}],
      ['LDPR',CL,'The third party in the Duma; its first Duma campaign led by Leonid Slutsky. Party-list vote: 8.9%.',B_LDPR]
    ],
    cap:[['Rodina','United Russia']],
    no:[['Yabloko','United Russia'],['Yabloko','LDPR'],['Yabloko','Rodina'],['Yabloko','Communists of Russia'],['CPRF','Yabloko'],['CPRF','United Russia'],['CPRF','Communists of Russia']],
    co:[['Pro-government majority',['United Russia','LDPR']],['Grand loyal coalition',['United Russia','LDPR','A Just Russia','New People']],['Renewed centre',['United Russia','New People']],
      ['Patriotic bloc',['United Russia','A Just Russia','LDPR']],['Left bloc',['CPRF','A Just Russia']],['Coalition of change',['CPRF','A Just Russia','New People']],
      ['Social bloc',['CPRF','A Just Russia','Party of Pensioners']],['Liberal bloc',['Yabloko','New People']],['Green centre',['New People','The Greens','Yabloko']]]},
  x2026:{thr:5,hide:1,qy:2027,name:'Duma-2026: snap elections',sys:'mixed',fic:1,note:'A fictional scenario: snap elections after the sudden death of Vladimir Putin, open to all political forces',
    F:[
      ['CPRF',CK,'The Communists count on the votes of those tired of both the former leadership and the liberals. The scenario is fictional.',tr(B_KPRF,{nation:2})],
      ['A Just Russia — For Truth',CS,'A social and patriotic agenda, aimed at supporters of continuing the previous course. The scenario is fictional.',tr(B_SR,{plural:1,stab:1,pres:1,sov:2,antiwest:2,nation:2,mil:2,trad:1})],
      ['Yabloko',CY,'The oldest democratic party: peace, human rights, a parliamentary republic. The scenario is fictional.',tr(B_YAB,{pac:3})],
      ['Democratic coalition','#D6336C','A fictional bloc: politicians of the non-system opposition who returned from exile or were released from prison. Free elections, peace, closer ties with Europe.',{plural:3,parl:3,lib:3,privacy:3,west:3,euro:3,rehab:3,pac:3,fed:3,mkt:2,biz:2,prog:2,cosmo:2,direct:2,sec:1,welfare:1,priv:1}],
      ['New People','#19B5A5','Moderate reformers: business, cities, cautious liberalisation without sharp turns. The scenario is fictional.',{mkt:2,biz:3,tax_lo:2,tech:3,plural:2,lib:2,fed:2,prog:1,choice:1,growth:2,direct:1,welfare:1,stab:1}],
      ['United Russia',CE,'The party of power without its central figure: the government, governors and the apparatus promise continuity and order. The scenario is fictional.',tr(B_ER,{antiwest:2,sov:3,nation:1,trad:3,tech:2})],
      ['LDPR',CL,'Leonid Slutsky’s party: nationalism, a tough migration policy, support for the army. The scenario is fictional.',B_LDPR],
      ['Russian Patriotic Bloc','#7A5230','A fictional bloc: war correspondents, volunteers and Orthodox monarchists who demand that the previous foreign policy continue with no concessions.',{nation:3,mil:3,sov:3,antiwest:3,trad:3,rel:3,auth:3,law:3,unity:3,prot:3,imm_anti:3,lang_one:3,cent:2,gos:2,assim:2,pres:2,eurasia:1,welfare:1}]
    ],
    no:[['Democratic coalition','Russian Patriotic Bloc'],['Democratic coalition','LDPR'],['Democratic coalition','CPRF'],['Democratic coalition','United Russia'],['Yabloko','Russian Patriotic Bloc'],['Yabloko','LDPR'],['New People','Russian Patriotic Bloc']],
    co:[['Continuity coalition',['United Russia','LDPR','A Just Russia — For Truth']],['Government of national unity',['United Russia','CPRF','LDPR','A Just Russia — For Truth','New People']],
      ['Coalition of change',['Democratic coalition','Yabloko','New People']],['Technocratic centre',['United Russia','New People']],['Transitional government',['United Russia','New People','Yabloko']],
      ['Left bloc',['CPRF','A Just Russia — For Truth']],['Patriotic majority',['United Russia','Russian Patriotic Bloc','LDPR']],['Stay-the-course bloc',['Russian Patriotic Bloc','LDPR','A Just Russia — For Truth']],['Democratic bloc',['Democratic coalition','Yabloko']]]}
};
// Персонажи партий по годам: [имя, код профильного портфеля или '']. Первый в списке — лидер.
const DUMA_P={
  1993:{'CPRF':[['Gennady Zyuganov',''],['Valentin Kuptsov',''],['Anatoly Lukyanov','jus'],['Viktor Ilyukhin','int'],['Gennady Seleznyov',''],['Viktor Zorkaltsev',''],['Oleg Mironov','']],
    'Agrarian Party':[['Mikhail Lapshin','agr'],['Ivan Rybkin',''],['Alexander Zaveryukha','agr'],['Vasily Starodubtsev',''],['Nikolai Kharitonov',''],['Gennady Kulik','fin']],
    'Women of Russia':[['Alevtina Fedulova',''],['Yekaterina Lakhova','soc'],['Natalya Gundareva','cul'],['Galina Klimantova','']],
    'DPR':[['Nikolai Travkin',''],['Sergei Glazyev','eco'],['Stanislav Govorukhin','cul'],['Oleg Bogomolov','fin']],
    'Yabloko':[['Grigory Yavlinsky','eco'],['Yuri Boldyrev',''],['Vladimir Lukin','for'],['Tatyana Yarygina','soc'],['Viktor Sheinis','jus'],['Alexei Arbatov','def'],['Nikolai Petrakov','fin']],
    'PRES':[['Sergei Shakhrai','ter'],['Alexander Shokhin','eco'],['Sergei Stankevich',''],['Konstantin Zatulin','for'],['Yuri Kalmykov','jus']],
    'Russia’s Choice':[['Yegor Gaidar','eco'],['Anatoly Chubais',''],['Andrei Kozyrev','for'],['Boris Fyodorov','fin'],['Sergei Kovalyov','jus'],['Ella Pamfilova','soc'],['Sergei Yushenkov','def'],['Mikhail Poltoranin','cul'],['Gennady Burbulis','']],
    'LDPR':[['Vladimir Zhirinovsky',''],['Alexander Vengerovsky',''],['Alexei Mitrofanov','for'],['Viktor Kobelev',''],['Stanislav Zhebrovsky',''],['Vladimir Gusev','eco']]},
  1995:{'CPRF':[['Gennady Zyuganov',''],['Svetlana Goryacheva','jus'],['Aman Tuleyev','ter'],['Gennady Seleznyov',''],['Yuri Maslyukov','eco'],['Valentin Kuptsov',''],['Anatoly Lukyanov',''],['Ivan Melnikov','edu'],['Viktor Ilyukhin','int']],
    'Agrarian Party':[['Mikhail Lapshin',''],['Nikolai Kharitonov',''],['Alexander Nazarchuk','agr'],['Vasily Starodubtsev',''],['Gennady Kulik','fin']],
    'Women of Russia':[['Alevtina Fedulova',''],['Yekaterina Lakhova','soc'],['Galina Klimantova','']],
    'Yabloko':[['Grigory Yavlinsky','eco'],['Vladimir Lukin','for'],['Tatyana Yarygina','soc'],['Sergei Ivanenko',''],['Oksana Dmitriyeva','fin'],['Viktor Sheinis',''],['Alexei Arbatov','def'],['Yelena Mizulina','jus'],['Vyacheslav Igrunov','']],
    'Democratic Choice of Russia':[['Yegor Gaidar','fin'],['Sergei Kovalyov','jus'],['Lidia Fedoseyeva-Shukshina','cul'],['Sergei Yushenkov','def'],['Anatoly Chubais','eco'],['Arkady Murashyov','int']],
    'Our Home — Russia':[['Viktor Chernomyrdin',''],['Nikita Mikhalkov','cul'],['Lev Rokhlin','def'],['Alexander Shokhin','eco'],['Sergei Belyayev',''],['Vladimir Ryzhkov',''],['Alexei Golovkov','fin']],
    'LDPR':[['Vladimir Zhirinovsky',''],['Alexei Mitrofanov','for'],['Sergei Kalashnikov','soc'],['Mikhail Gutseriyev','eco'],['Stanislav Zhebrovsky',''],['Vladimir Gusev','']]},
  1999:{'CPRF':[['Gennady Zyuganov',''],['Gennady Seleznyov',''],['Vasily Starodubtsev','agr'],['Sergei Glazyev','eco'],['Yuri Maslyukov','fin'],['Valentin Kuptsov',''],['Ivan Melnikov','edu'],['Viktor Ilyukhin','int'],['Anatoly Lukyanov','jus'],['Nikolai Kharitonov','']],
    'Fatherland — All Russia':[['Yevgeny Primakov','for'],['Yuri Luzhkov',''],['Vladimir Yakovlev','ter'],['Yekaterina Lakhova','soc'],['Vyacheslav Volodin',''],['Konstantin Kosachyov',''],['Georgy Boos','fin'],['Stanislav Govorukhin','cul'],['Mintimer Shaimiyev','']],
    'Yabloko':[['Grigory Yavlinsky','eco'],['Sergei Stepashin','int'],['Vladimir Lukin','for'],['Nikolai Travkin',''],['Sergei Ivanenko',''],['Alexei Arbatov','def'],['Sergei Mitrokhin',''],['Igor Artemyev','fin']],
    'Union of Right Forces':[['Sergei Kiriyenko',''],['Boris Nemtsov',''],['Irina Khakamada','soc'],['Yegor Gaidar','fin'],['Anatoly Chubais','eco'],['Pavel Krasheninnikov','jus'],['Viktor Pokhmelkin',''],['Konstantin Titov','ter']],
    'Unity':[['Sergei Shoigu',''],['Alexander Karelin','cul'],['Alexander Gurov','int'],['Boris Gryzlov',''],['Lyubov Sliska',''],['Vladimir Pekhtin',''],['Frants Klintsevich','def']],
    'Zhirinovsky Bloc':[['Vladimir Zhirinovsky',''],['Alexei Mitrofanov','for'],['Oleg Finko',''],['Yegor Solomatin',''],['Igor Lebedev','']]},
  2003:{'CPRF':[['Gennady Zyuganov',''],['Nikolai Kondratenko',''],['Nikolai Kharitonov','agr'],['Ivan Melnikov','edu'],['Valentin Kuptsov',''],['Viktor Ilyukhin','int'],['Svetlana Savitskaya','def'],['Zhores Alfyorov','']],
    'Agrarian Party':[['Mikhail Lapshin','agr'],['Vladimir Plotnikov','']],
    'Rodina':[['Sergei Glazyev','eco'],['Dmitry Rogozin','for'],['Valentin Varennikov','def'],['Sergei Baburin',''],['Natalya Narochnitskaya','cul'],['Oleg Shein','soc'],['Viktor Gerashchenko','fin'],['Andrei Savelyev',''],['Georgy Shpak',''],['Alexander Babakov','']],
    'Yabloko':[['Grigory Yavlinsky',''],['Vladimir Lukin','for'],['Igor Artemyev','eco'],['Sergei Mitrokhin',''],['Sergei Ivanenko',''],['Alexei Arbatov','def'],['Sergei Popov','jus']],
    'United Russia':[['Boris Gryzlov','int'],['Sergei Shoigu','def'],['Yuri Luzhkov',''],['Mintimer Shaimiyev','ter'],['Alexander Zhukov','fin'],['Lyubov Sliska',''],['Vyacheslav Volodin',''],['Oleg Morozov',''],['Andrei Isayev','soc'],['Vladimir Pekhtin','']],
    'Union of Right Forces':[['Boris Nemtsov',''],['Irina Khakamada','soc'],['Anatoly Chubais','eco'],['Yegor Gaidar','fin'],['Leonid Gozman','']],
    'LDPR':[['Vladimir Zhirinovsky',''],['Alexei Ostrovsky',''],['Igor Lebedev',''],['Alexei Mitrofanov','for'],['Sergei Abeltsev','int'],['Oleg Malyshkin','']]},
  2007:{'CPRF':[['Gennady Zyuganov',''],['Zhores Alfyorov','edu'],['Nikolai Kharitonov','agr'],['Ivan Melnikov',''],['Viktor Ilyukhin','int'],['Svetlana Savitskaya','def'],['Vladimir Kashin',''],['Valery Rashkin','']],
    'Agrarian Party':[['Vladimir Plotnikov','agr'],['Nina Brusnikova','']],
    'A Just Russia':[['Sergei Mironov',''],['Svetlana Goryacheva','jus'],['Nikolai Levichev',''],['Oksana Dmitriyeva','fin'],['Galina Khovanskaya','soc'],['Gennady Gudkov','int'],['Yelena Mizulina',''],['Ivan Grachyov','eco'],['Oleg Shein',''],['Yelena Drapeko','cul']],
    'Yabloko':[['Grigory Yavlinsky','eco'],['Sergei Kovalyov','jus'],['Sergei Ivanenko',''],['Sergei Mitrokhin',''],['Alexei Yablokov','env']],
    'United Russia':[['Vladimir Putin',''],['Boris Gryzlov','int'],['Sergei Shoigu','def'],['Vyacheslav Volodin',''],['Andrei Isayev','soc'],['Oleg Morozov',''],['Lyubov Sliska',''],['Andrei Vorobyov',''],['Pavel Krasheninnikov','jus'],['Svetlana Zhurova','cul'],['Vladimir Pekhtin','']],
    'Union of Right Forces':[['Nikita Belykh',''],['Boris Nemtsov','eco'],['Marietta Chudakova','cul'],['Leonid Gozman',''],['Maria Gaidar','soc']],
    'LDPR':[['Vladimir Zhirinovsky',''],['Andrei Lugovoi','int'],['Igor Lebedev',''],['Alexei Ostrovsky',''],['Sergei Abeltsev',''],['Leonid Slutsky','for']]},
  2011:{'CPRF':[['Gennady Zyuganov',''],['Vladimir Komoyedov','def'],['Yuri Afonin',''],['Ivan Melnikov','edu'],['Zhores Alfyorov',''],['Valery Rashkin',''],['Sergei Obukhov',''],['Vladimir Kashin','agr'],['Nikolai Kharitonov',''],['Svetlana Savitskaya','']],
    'Patriots of Russia':[['Gennady Semigin',''],['Sergei Makhovikov','cul'],['Nadezhda Korneyeva','']],
    'A Just Russia':[['Sergei Mironov',''],['Nikolai Levichev',''],['Oksana Dmitriyeva','fin'],['Gennady Gudkov','int'],['Yelena Mizulina','soc'],['Galina Khovanskaya',''],['Ilya Ponomaryov',''],['Oleg Shein',''],['Yelena Drapeko','cul'],['Dmitry Gudkov','']],
    'Yabloko':[['Grigory Yavlinsky','eco'],['Sergei Mitrokhin',''],['Alexei Yablokov','env'],['Sergei Ivanenko',''],['Boris Vishnevsky',''],['Lev Shlosberg','ter']],
    'United Russia':[['Dmitry Medvedev',''],['Boris Gryzlov',''],['Sergei Naryshkin',''],['Vyacheslav Volodin',''],['Sergei Neverov',''],['Andrei Isayev','soc'],['Irina Yarovaya','int'],['Pavel Krasheninnikov','jus'],['Svetlana Zhurova','cul'],['Alexander Zhukov','fin']],
    'Right Cause':[['Andrei Dunayev',''],['Andrei Bogdanov','']],
    'LDPR':[['Vladimir Zhirinovsky',''],['Alexei Ostrovsky',''],['Igor Lebedev',''],['Leonid Slutsky','for'],['Yaroslav Nilov','soc'],['Mikhail Degtyaryov',''],['Andrei Lugovoi','int']]},
  2016:{'CPRF':[['Gennady Zyuganov',''],['Svetlana Savitskaya','def'],['Yuri Afonin',''],['Zhores Alfyorov','edu'],['Ivan Melnikov',''],['Valery Rashkin',''],['Vladimir Kashin','agr'],['Nikolai Kharitonov',''],['Vera Ganzya','']],
    'A Just Russia':[['Sergei Mironov',''],['Galina Khovanskaya','soc'],['Yelena Drapeko','cul'],['Valery Gartung','eco'],['Oleg Nilov',''],['Alexander Burkov',''],['Oleg Shein',''],['Mikhail Yemelyanov','jus']],
    'Yabloko':[['Emilia Slabunova','edu'],['Grigory Yavlinsky','eco'],['Vladimir Ryzhkov',''],['Dmitry Gudkov',''],['Lev Shlosberg','ter'],['Sergei Mitrokhin',''],['Boris Vishnevsky',''],['Galina Shirshina','']],
    'Party of Growth':[['Boris Titov','eco'],['Oksana Dmitriyeva','fin'],['Irina Khakamada','soc'],['Dmitry Potapenko','']],
    'United Russia':[['Dmitry Medvedev',''],['Vyacheslav Volodin',''],['Sergei Neverov',''],['Irina Yarovaya','int'],['Andrei Isayev','soc'],['Pavel Krasheninnikov','jus'],['Alexander Zhukov','fin'],['Vyacheslav Nikonov','edu'],['Natalya Poklonskaya','']],
    'Rodina':[['Alexei Zhuravlyov','def']],
    'LDPR':[['Vladimir Zhirinovsky',''],['Igor Lebedev',''],['Leonid Slutsky','for'],['Yaroslav Nilov','soc'],['Mikhail Degtyaryov',''],['Alexei Didenko','ter'],['Vadim Dengin',''],['Andrei Lugovoi','int']]},
  2021:{'CPRF':[['Gennady Zyuganov',''],['Svetlana Savitskaya','def'],['Yuri Afonin',''],['Sergei Levchenko','ter'],['Nina Ostanina','soc'],['Valery Rashkin',''],['Vladimir Kashin','agr'],['Nikolai Kharitonov',''],['Ivan Melnikov','edu'],['Denis Parfyonov','']],
    'A Just Russia — For Truth':[['Sergei Mironov',''],['Zakhar Prilepin','cul'],['Gennady Semigin',''],['Galina Khovanskaya','soc'],['Alexander Babakov','fin'],['Oleg Nilov',''],['Valery Gartung','eco'],['Yana Lantratova',''],['Nikolai Burlyayev',''],['Anatoly Vasserman','edu']],
    'Yabloko':[['Nikolai Rybakov','env'],['Grigory Yavlinsky','eco'],['Boris Vishnevsky',''],['Lev Shlosberg','ter'],['Sergei Mitrokhin',''],['Emilia Slabunova','edu'],['Alexander Shishlov','']],
    'New People':[['Alexei Nechayev',''],['Sardana Avksentyeva','ter'],['Vladislav Davankov',''],['Sangadzhi Tarbayev','cul'],['Ksenia Goryacheva','edu'],['Anton Tkachyov',''],['Georgy Arapov',''],['Alexander Dyomin','eco']],
    'United Russia':[['Dmitry Medvedev',''],['Sergei Shoigu','def'],['Sergei Lavrov','for'],['Denis Protsenko','hea'],['Yelena Shmelyova','edu'],['Anna Kuznetsova','soc'],['Vyacheslav Volodin',''],['Andrei Isayev',''],['Pavel Krasheninnikov','jus'],['Irina Yarovaya','int'],['Alexander Zhukov','fin'],['Oleg Morozov','']],
    'Party of Growth':[['Boris Titov','eco'],['Oksana Dmitriyeva','fin']],
    'LDPR':[['Vladimir Zhirinovsky',''],['Leonid Slutsky','for'],['Yaroslav Nilov','soc'],['Alexei Didenko','ter'],['Vasily Vlasov',''],['Andrei Lugovoi','int'],['Boris Chernyshov','edu']]},
  2026:{'CPRF':[['Gennady Zyuganov',''],['Yuri Afonin',''],['Nikolai Kharitonov',''],['Nina Ostanina','soc'],['Vladimir Kashin','agr'],['Sergei Levchenko','ter'],['Ivan Melnikov','edu'],['Svetlana Savitskaya','def'],['Dmitry Novikov','for'],['Denis Parfyonov','']],
    'A Just Russia':[['Sergei Mironov',''],['Zakhar Prilepin','cul'],['Galina Khovanskaya','soc'],['Alexander Babakov','fin'],['Oleg Nilov',''],['Valery Gartung','eco'],['Yana Lantratova',''],['Anatoly Vasserman','edu']],
    'Yabloko':[['Nikolai Rybakov','env'],['Grigory Yavlinsky','eco'],['Lev Shlosberg','ter'],['Boris Vishnevsky',''],['Sergei Mitrokhin',''],['Emilia Slabunova','edu'],['Alexander Shishlov','']],
    'New People':[['Alexei Nechayev',''],['Vladislav Davankov',''],['Sardana Avksentyeva','ter'],['Sangadzhi Tarbayev','cul'],['Ksenia Goryacheva','edu'],['Anton Tkachyov',''],['Georgy Arapov',''],['Alexander Dyomin','eco']],
    'United Russia':[['Dmitry Medvedev',''],['Vyacheslav Volodin',''],['Sergei Lavrov','for'],['Sergei Sobyanin','ter'],['Andrei Belousov','def'],['Anton Siluanov','fin'],['Maxim Reshetnikov','eco'],['Andrei Turchak',''],['Irina Yarovaya','int'],['Pavel Krasheninnikov','jus'],['Anna Kuznetsova','soc'],['Denis Manturov','']],
    'Rodina':[['Alexei Zhuravlyov','def']],
    'The Greens':[['Andrei Nagibin','env']],
    'Communists of Russia':[['Sergei Malinkovich','']],
    'LDPR':[['Leonid Slutsky',''],['Yaroslav Nilov','soc'],['Alexei Didenko','ter'],['Boris Chernyshov','edu'],['Mikhail Degtyaryov',''],['Vasily Vlasov',''],['Andrei Lugovoi','int']]},
  x2026:{'CPRF':[['Gennady Zyuganov',''],['Yuri Afonin',''],['Nikolai Kharitonov',''],['Nina Ostanina','soc'],['Vladimir Kashin','agr'],['Sergei Levchenko','ter'],['Ivan Melnikov','edu'],['Svetlana Savitskaya','def'],['Dmitry Novikov','for'],['Denis Parfyonov','']],
    'A Just Russia — For Truth':[['Sergei Mironov',''],['Zakhar Prilepin','cul'],['Galina Khovanskaya','soc'],['Alexander Babakov','fin'],['Oleg Nilov',''],['Valery Gartung','eco'],['Yana Lantratova',''],['Anatoly Vasserman','edu']],
    'Yabloko':[['Nikolai Rybakov','env'],['Grigory Yavlinsky','eco'],['Lev Shlosberg','ter'],['Boris Vishnevsky',''],['Sergei Mitrokhin',''],['Emilia Slabunova','edu'],['Alexander Shishlov','']],
    'Democratic coalition':[['Yulia Navalnaya',''],['Ilya Yashin',''],['Vladimir Kara-Murza','for'],['Boris Nadezhdin',''],['Yekaterina Duntsova','soc'],['Mikhail Khodorkovsky','eco'],['Sergei Guriev','fin'],['Lyubov Sobol','jus'],['Yevgeny Roizman','ter'],['Andrei Pivovarov',''],['Maxim Katz',''],['Dmitry Gudkov','']],
    'New People':[['Alexei Nechayev',''],['Vladislav Davankov',''],['Sardana Avksentyeva','ter'],['Sangadzhi Tarbayev','cul'],['Ksenia Goryacheva','edu'],['Anton Tkachyov',''],['Georgy Arapov',''],['Alexander Dyomin','eco']],
    'United Russia':[['Dmitry Medvedev',''],['Mikhail Mishustin',''],['Sergei Sobyanin','ter'],['Andrei Belousov','def'],['Sergei Lavrov','for'],['Anton Siluanov','fin'],['Maxim Reshetnikov','eco'],['Vyacheslav Volodin',''],['Sergei Kiriyenko',''],['Andrei Turchak',''],['Irina Yarovaya','int'],['Pavel Krasheninnikov','jus'],['Anna Kuznetsova','soc'],['Denis Manturov','']],
    'LDPR':[['Leonid Slutsky',''],['Yaroslav Nilov','soc'],['Alexei Didenko','ter'],['Boris Chernyshov','edu'],['Mikhail Degtyaryov',''],['Vasily Vlasov',''],['Andrei Lugovoi','int']],
    'Russian Patriotic Bloc':[['Konstantin Malofeyev',''],['Igor Strelkov','def'],['Sergei Glazyev','eco'],['Alexander Dugin','edu'],['Alexander Prokhanov','cul'],['Alexander Borodai',''],['Sergei Aksyonov','ter'],['Alexei Zhuravlyov','']]}
};
const BUILTIN=Object.keys(DUMA).map(y=>{ const D=DUMA[y], yr=parseInt(String(y).replace(/\D/g,''),10), qy=D.qy||yr; // ключ с буквой — второй сценарий того же года
  return {h:D.hide?1:0,n:D.name||'Duma-'+yr,d:D.note+' · '+(D.sys==='mixed'?'party list and districts':'party lists only')+' · '+D.F.length+' parties',
    set:{seats:450,sys:D.sys,party:'multi',year:yr,span:false,thr:D.thr||0,thron:!!D.thr,key:String(yr)===String(y)?'':String(y)},
    raw:{T:DT,F:D.F,Q:DQ.filter(q=>q[0]<=qy&&qy<=q[1]).map(q=>q.slice(2)),no:D.no,co:D.co,P:DUMA_P[y]||{},cap:D.cap,gate:D.gate}}; }).concat([
  {n:'Standard',d:'Based on the Spanish test “Tu hemiciclo” (objetivo176.es): six questions choose the system, followed by 48 questions and seven European parties',set:{seats:350,sys:'prop',party:'auto'}},
  {h:1,n:'As in the original',d:'350 seats by party list, many parties',set:{seats:350,sys:'prop',party:'multi'}},
  {h:1,n:'Question = seat',d:'96 seats: 48 by party list and 48 question-districts',set:{seats:96,sys:'mixed',party:'multi'}},
  {h:1,n:'Two parties',d:'435 seats shared by two rival parties',set:{seats:435,sys:'prop',party:'two'}},
  {h:1,n:'Dominant party',d:'350 seats, the leader is guaranteed a majority',set:{seats:350,sys:'prop',party:'dom'}},
  {h:1,n:'One party',d:'All 300 seats go to the closest party',set:{seats:300,sys:'prop',party:'one'}}
]);
